<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\CarModel;


class CarModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        CarModel::insert(self::$carModels);
    }

    
    /**
     * The car model data.
     *
     * @var array
     */
    protected static $carModels = [
        [
            'brand' => 'Nissan',
            'model_name' => 'Almera',
            'model_year' => '2025',
            'model_desc' => 'VL Sport Turbo CVT',
            'color' => 'Moon Pearl Gray',
            'engine_type' => '3-Cylinder Gasoline',
            'engine_displacement' => 998,
            'fuel_type' => 'Gasoline',
            'transmission' => 'CVT',
            'seat_capacity' => 5,
            'car_dimensions' => '4,495 mm x 1,740 mm',
            'car_type' => 'Sedan',
            'img_file_path' => 'assets/car_model_images/nissan_almera_2025.avif',
        ],
        [
            'brand' => 'Toyota',
            'model_name' => 'Vios',
            'model_year' => '2025',
            'model_desc' => '1.3 XLE CVT',
            'color' => 'Attitude Black Mica',
            'engine_type' => 'Dual VVT-i, 4-Cylinder In-Line DOHC 16V EFI',
            'engine_displacement' => 1329,
            'fuel_type' => 'Gasoline',
            'transmission' => 'CVT',
            'seat_capacity' => 5,
            'car_dimensions' => '4,420 mm x 1,730 mm x 1,475 mm',
            'car_type' => 'Sedan',
            'img_file_path' => 'assets/car_model_images/toyota_vios_2025.png',
        ],
        [
            'brand' => 'Honda',
            'model_name' => 'City',
            'model_year' => '2024',
            'model_desc' => '1.5 RS CVT Honda SENSING',
            'color' => 'White',
            'engine_type' => 'In-Line 4-Cylinder',
            'engine_displacement' => 1498,
            'fuel_type' => 'Gasoline',
            'transmission' => 'CVT',
            'seat_capacity' => 5,
            'car_dimensions' => '4,589 mm x 1,748 mm x 1,467 mm',
            'car_type' => 'Sedan',
            'img_file_path' => 'assets/car_model_images/honda_city_2024.png',
        ],
        [
            'brand' => 'Suzuki',
            'model_name' => 'Dzire',
            'model_year' => '2022',
            'model_desc' => 'GL',
            'color' => 'Magma Grey',
            'engine_type' => 'In-line 4-Cylinder',
            'engine_displacement' => 1197,
            'fuel_type' => 'Gasoline',
            'transmission' => 'Manual',
            'seat_capacity' => 5,
            'car_dimensions' => '3,995 mm x 1,735 mm x 1,515 mm',
            'car_type' => 'Sedan',
            'img_file_path' => 'assets/car_model_images/suzuki_dzire_2022.png',
        ],
        [
            'brand' => 'Nissan',
            'model_name' => 'Kicks',
            'model_year' => 2024,
            'model_desc' => 'e-POWER VL',
            'color' => 'White',
            'engine_type' => '3-Cylinder DOHC 12-Valve CVTC with Electric Motor',
            'engine_displacement' => 1198,
            'fuel_type' => 'Gasoline',
            'transmission' => 'Automatic',
            'seat_capacity' => 5,
            'car_dimensions' => '4,300 mm x 1,760 mm x 1,615 mm',
            'car_type' => 'SUV',
            'img_file_path' => 'assets/car_model_images/nissan_kicks_2024.png',
        ],
        [
            'brand' => 'Mitsubishi',
            'model_name' => 'Montero Sport',
            'model_year' => 2022,
            'model_desc' => '4WD 8AT',
            'color' => 'Black',
            'engine_type' => '4-Cylinder',
            'engine_displacement' => 2398,
            'fuel_type' => 'Diesel',
            'transmission' => 'Automatic',
            'seat_capacity' => 7,
            'car_dimensions' => '4,825 mm x 1,815 mm',
            'car_type' => 'SUV',
            'img_file_path' => 'assets/car_model_images/mitsubishi_montero_sport_2024.png',
        ],
        [
            'brand' => 'Suzuki',
            'model_name' => 'Jimny',
            'model_year' => 2023,
            'model_desc' => 'GLX AT Rhino Edition',
            'color' => 'Chiffon Ivory Metallic',
            'engine_type' => '4-Cylinder',
            'engine_displacement' => 1462,
            'fuel_type' => 'Diesel',
            'transmission' => 'Automatic',
            'seat_capacity' => 4,
            'car_dimensions' => '3,650 mm x 1,645 mm',
            'car_type' => 'SUV',
            'img_file_path' => 'assets/car_model_images/suzuki_jimny_rhino_2023.png',
        ],
        [
            'brand' => 'Toyota',
            'model_name' => 'Fortuner',
            'model_year' => '2024',
            'model_desc' => 'LTD 4x4 AT',
            'color' => 'Silver Metallic',
            'engine_type' => '4-Cylinder, 16-Valve DOHC, Variable Nozzle Turbo with Intercooler',
            'engine_displacement' => 2755,
            'fuel_type' => 'Diesel',
            'transmission' => 'Automatic',
            'seat_capacity' => 7,
            'car_dimensions' => '4,795 mm x 1,855 mm x 1,835 mm',
            'car_type' => 'SUV',
            'img_file_path' => 'assets/car_model_images/toyota_fortuner_2024.png',
        ],
        [
            'brand' => 'Ford',
            'model_name' => 'Everest',
            'model_year' => '2022',
            'model_desc' => '2.0L Bi-Turbo Titanium+ 4x4 AT',
            'color' => 'Aluminum Metallic',
            'engine_type' => '2.0L Bi-Turbo Diesel',
            'engine_displacement' => 1996,
            'fuel_type' => 'Diesel',
            'transmission' => 'Automatic',
            'seat_capacity' => 7,
            'car_dimensions' => '4,914 mm x 1,923 mm x 1,836 mm',
            'car_type' => 'SUV',
            'img_file_path' => 'assets/car_model_images/ford_everest_2022.png',
        ],
        [
            'brand' => 'Honda',
            'model_name' => 'HR-V',
            'model_year' => '2024',
            'model_desc' => 'RS Turbo CVT',
            'color' => 'Urban Gray Pearl',
            'engine_type' => '1.5L VTEC Turbocharged Gasoline',
            'engine_displacement' => 1498,
            'fuel_type' => 'Gasoline',
            'transmission' => 'CVT',
            'seat_capacity' => 5,
            'car_dimensions' => '4,385 mm x 1,790 mm x 1,590 mm',
            'car_type' => 'SUV',
            'img_file_path' => 'assets/car_model_images/honda_hrv_2024.png',
        ],
        [
            'brand' => 'Nissan',
            'model_name' => 'Navara',
            'model_year' => '2024',
            'model_desc' => '2.5L Pro-4X AT 4x4',
            'color' => 'Stealth Pearl Gray',
            'engine_type' => '4-Cylinder Diesel',
            'engine_displacement' => 2488,
            'fuel_type' => 'Diesel',
            'transmission' => 'Automatic',
            'seat_capacity' => 5,
            'car_dimensions' => '5,260 mm x 1,875 mm',
            'car_type' => 'Pick-up',
            'img_file_path' => 'assets/car_model_images/nissan_navara_2024.png',
        ],
        [
            'brand' => 'Ford',
            'model_name' => 'Ranger',
            'model_year' => '2023',
            'model_desc' => '2.0L Bi-Turbo Wildtrak 4x4 AT',
            'color' => 'Luxe Yellow',
            'engine_type' => '4-Cylinder Diesel',
            'engine_displacement' => 1996,
            'fuel_type' => 'Diesel',
            'transmission' => 'Automatic',
            'seat_capacity' => 5,
            'car_dimensions' => '5,370 mm x 1,918 mm',
            'car_type' => 'Pick-up',
            'img_file_path' => 'assets/car_model_images/ford_ranger_wildtrak_2023.png',
        ],
        // [
        //     'brand' => '',
        //     'model_name' => '',
        //     'model_year' => '',
        //     'model_desc' => '',
        //     'color' => '',
        //     'engine_type' => '',
        //     'engine_displacement' => '',
        //     'fuel_type' => '',
        //     'transmission' => '',
        //     'seat_capacity' => '',
        //     'car_dimensions' => '',
        //     'car_type' => '',
        //     'img_file_path' => 'assets/car_model_images/',
        // ],
        // [
        //     'brand' => '',
        //     'model_name' => '',
        //     'model_year' => '',
        //     'model_desc' => '',
        //     'color' => '',
        //     'engine_type' => '',
        //     'engine_displacement' => '',
        //     'fuel_type' => '',
        //     'transmission' => '',
        //     'seat_capacity' => '',
        //     'car_dimensions' => '',
        //     'car_type' => '',
        //     'img_file_path' => 'assets/car_model_images/',
        // ],
    ];
}
